hid all in git secrets

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -10,18 +10,18 @@ jobs:
       - name: Checkout code
         uses: actions/checkout@v4
 
-      - name: Create .env file
+      - name: Create .env file from secrets
         run: |
           cat << EOF > .env
-          DB_HOST=database
-          DB_PORT=5432
-          DB_USER=ffink
-          DB_PASS=1111
-          DB_NAME=puzzles_site
-          DATABASE_URL=postgresql+asyncpg://ffink:1111@database:5432/puzzles_site
-          REDIS_HOST=redis
-          MODE=DEV
-          SECRET_KEY="CyhFX83gSKiOBAsErJcxwQ2IWIfnH7razpoqGSFicR0="
+          DB_HOST=${{ secrets.DB_HOST }}
+          DB_PORT=${{ secrets.DB_PORT }}
+          DB_USER=${{ secrets.DB_USER }}
+          DB_PASS=${{ secrets.DB_PASS }}
+          DB_NAME=${{ secrets.DB_NAME }}
+          DATABASE_URL=${{ secrets.DATABASE_URL }}
+          REDIS_HOST=${{ secrets.REDIS_HOST }}
+          MODE=${{ secrets.MODE }}
+          SECRET_KEY=${{ secrets.SECRET_KEY }}
           EOF
 
       - name: Build and start services required for tests
@@ -30,7 +30,7 @@ jobs:
       - name: Wait for database to be ready
         run: |
           for i in {1..30}; do
-            if docker compose exec -T database pg_isready -U ffink; then
+            if docker compose exec -T database pg_isready -U ${{ secrets.DB_USER }}; then
               echo "Database is ready"
               break
             fi
@@ -39,7 +39,16 @@ jobs:
           done
 
       - name: Wait for backend to be ready
-        run: sleep 10   # заменить на curl healthcheck если есть эндпоинт
+        run: |
+          for i in {1..20}; do
+            if curl -s http://localhost:8000/health; then
+              echo "Backend is ready"
+              exit 0
+            fi
+            echo "Attempt $i: backend not ready yet"
+            sleep 1
+          done
+          echo "Backend failed to start" && exit 1
 
       - name: Run tests
         run: docker compose exec -T backend pytest
